services:

  app:
    build:
      context: .
      args:
        progress: plain
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - path: compose.env
        required: true # default
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
