FROM python:3.12-slim
RUN pip install poetry && apt update 

# Set up working directory
WORKDIR /app
# Copy application files
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false && \
    poetry install --no-root && \
    playwright install --with-deps chromium

# Copy application code
COPY . .

RUN poetry config virtualenvs.create false && poetry install
ENTRYPOINT [ "/usr/bin/bash", "-c", "python app/telegram_bot/main.py" ]
