"""
This type stub file was generated by pyright.
"""

import importlib.util
import inspect
import re
from pathlib import Path
from typing import Type
from wiktionary_de_parser.models import ParsedWiktionaryPageEntry, WiktionaryPage, WiktionaryPageEntry
from wiktionary_de_parser.parser import Parser

class WiktionaryParser:
    parser_classes: list[Type[Parser]]
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def find_parser_classes(): # -> list[Any]:
        ...
    
    def entries_from_page(self, page: WiktionaryPage): # -> Generator[WiktionaryPageEntry, Any, None]:
        """
        Split page into entries. One page can have multiple word entries, for example:
            - https://de.wiktionary.org/wiki/instrument

        New entries begin at "==" and "===" (sometimes there is no "==")
        Compare:
            - https://de.wiktionary.org/wiki/instrument
            - https://de.wiktionary.org/wiki/Becken
        """
        ...
    
    def parse_entry(self, wiktionary_entry: WiktionaryPageEntry): # -> ParsedWiktionaryPageEntry:
        """
        Parses an entry of a page.
        """
        ...
    


