"""
This type stub file was generated by pyright.
"""

import re
from dataclasses import dataclass, field
from wiktionary_de_parser.models import WiktionaryPageEntry

@dataclass(slots=True)
class Parser:
    entry: WiktionaryPageEntry
    name: str = ...
    def run(self):
        ...
    
    @staticmethod
    def find_paragraph(heading: str, wikitext: str) -> str | None:
        ...
    
    @staticmethod
    def strip_html_tags(text: str): # -> str:
        ...
    


